### ISSUE TITLE
Should there be a separate branch for Tizen port?

### ISSUE THREAD

**Issue by ozbek** [TizenTeam/voice-memos#1]
Hello.

As the title says, should there be a dedicated branch (e.g., `tizen`) for Tizen (Web app?!) port? This will enable to keep `master` branch even with the upstream and easily track/pull changes from there.

What do you think?

**Comment by swift11** [comment]
Hi Shuhrat,
I don't think the upstream will change a lot: these Google apps are essentially demos:
https://aerotwist.com/blog/voice-memos/
It would be interesting to build something different from this base, with better codecs for instance:
"the app has to store audio as WAVs, so don’t record long memos ! I’m sorry about that, but there’s nothing I can do about this just yet."

**Comment by ozbek** [comment]
Fair enough :)
